package com.projectdummy.dummy.project.component;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.projectdummy.dummy.project.entity.Customer;
import com.projectdummy.dummy.project.repository.ICustomerRepository;
import com.projectdummy.dummy.project.service.CustomerService;
import org.apache.catalina.util.CustomObjectInputStream;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author uchen
 */
@Component
public class Dashboard extends javax.swing.JFrame {

    @Autowired
    private Customer customer;

    @Autowired
    private CustomerService customerService;

    @Autowired
    private LoginPage loginPage;

    @Autowired
    private ICustomerRepository iCustomerRepository;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        welcomeHeader = new javax.swing.JLabel();
        depositCahsButton = new javax.swing.JButton();
        checkBalance = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeHeader.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        welcomeHeader.setText("Welcome");

        depositCahsButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        depositCahsButton.setText("Deposit Cash");
        depositCahsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositCahsButtonActionPerformed(evt);
            }
        });

        checkBalance.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        checkBalance.setText("Check Balance");
        checkBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceActionPerformed(evt);
            }
        });

        withdrawButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(withdrawButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(depositCahsButton)
                                .addGap(38, 38, 38))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(checkBalance))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(185, 185, 185)
                                                .addComponent(welcomeHeader)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(welcomeHeader)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(depositCahsButton)
                                        .addComponent(withdrawButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(checkBalance)
                                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Enter how much you want to withdraw");
        Long.parseLong(input);
        long newBalance = loginPage.foundCustomer.getBalance();
        newBalance-=Long.parseLong(input);
        loginPage.foundCustomer.setBalance(newBalance);
        iCustomerRepository.save(loginPage.foundCustomer);
        JOptionPane.showInputDialog(jTextField1, "You have successfully withdrawn " + input + ", your new balance is " + loginPage.foundCustomer.getBalance());
    }

    private void depositCahsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         String input = JOptionPane.showInputDialog("Enter the amount to deposit");
         Long.parseLong(input);
         long newBalance = loginPage.foundCustomer.getBalance();
         newBalance+=Long.parseLong(input);
         loginPage.foundCustomer.setBalance(newBalance);
         iCustomerRepository.save(loginPage.foundCustomer);
         JOptionPane.showMessageDialog(jTextField1, "You have deposited " +  input + ", your new balance is " + loginPage.foundCustomer.getBalance());
    }

    private void checkBalanceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jTextField1, "Your account balance is: $ " +loginPage.foundCustomer.getBalance());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton checkBalance;
    private javax.swing.JButton depositCahsButton;
    private javax.swing.JLabel welcomeHeader;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField jTextField1;

    // End of variables declaration
}
