/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectdummy.dummy.project.component;

import com.projectdummy.dummy.project.Scanner.SecugenScanner;
import com.projectdummy.dummy.project.entity.Customer;
import com.projectdummy.dummy.project.entity.Fingerprint;
import com.projectdummy.dummy.project.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author uchen
 */
@Component
public class LoginPage extends JFrame {

    Customer foundCustomer;
    SecugenScanner scanner;
    int numberOfMatchedPrints = 0;
    int numberOfPrintsToValidate = 4;
    List<Fingerprint> prints  = new ArrayList<>();

    @Autowired
    CustomerService customerService ;

    @Autowired
    Dashboard dashboard;

    /**
     * Creates new form Login_page
     */
    public LoginPage() {
        initComponents();
        scanner = SecugenScanner.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        fingerDisplayPanel = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("                 LOGIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("   Please enter your userID and click on continue...");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButton(evt);
            }
        });

        jTextField1.setToolTipText("UserID");
        jTextField1.setToolTipText("");

        fingerDisplayPanel.setEnabled(true);
        fingerDisplayPanel.setBackground(new Color(0x999999));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(275, 275, 275)
                                                .addComponent(jButton1))
                                        .addComponent(fingerDisplayPanel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(124, Short.MAX_VALUE))
                                )));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(60, 60, 60)
                                .addComponent(fingerDisplayPanel)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    private void verifyPrints(){
        JOptionPane.showMessageDialog( jTextField1, "Place finger on scanner and Scan fingerprints...");

        scanner.sleep(1);
        byte[] scannedPrint  = scanner.captureBytes();

        for(int i = 0 ; i< prints.size(); i++){
            if(scanner.match(scannedPrint, prints.get(i).getPrintObject())){
                numberOfMatchedPrints++;
                prints.remove(i);
                System.out.println("Match Found: "+ numberOfMatchedPrints);
                break;
            }
        }

        if(numberOfMatchedPrints >= numberOfPrintsToValidate){
            dashboard.setVisible(true);
            return;
        }

        jLabel2.setText("Fingerprint matching failed");
        System.out.println("Done here");

    }

    private void resetPrintsCounts(){
        numberOfMatchedPrints = 0;
        prints = new ArrayList<>();
    }

    private void ContinueButton(java.awt.event.ActionEvent evt) {
       resetPrintsCounts();
        foundCustomer = customerService.searchCustomerByCode(jTextField1.getText());
        if(foundCustomer == null){
            jLabel2.setText("Customer not found!!!");
            return;
        }

        prints = foundCustomer.getFingerprints();

        for(int i=0; i<numberOfPrintsToValidate ; i++){
            verifyPrints();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>


//        fingerDisplayPanel.add(fingerDisplayPanel);
//        fingerDisplayPanel.revalidate();
//        fingerDisplayPanel.repaint();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private static javax.swing.JPanel fingerDisplayPanel;
    // End of variables declaration
}
