/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectdummy.dummy.project.component;

import com.projectdummy.dummy.project.Scanner.SecugenScanner;
import com.projectdummy.dummy.project.entity.Customer;
import com.projectdummy.dummy.project.entity.Fingerprint;
import com.projectdummy.dummy.project.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author uchen
 */
@Component
public class LoginPage extends javax.swing.JFrame {

    Customer foundCustomer;
    SecugenScanner scanner;
    int numberOfMatchedPrints = 0;
    int numberOfPrintsToValidate = 4;
    List<Fingerprint> prints = new ArrayList<>();

    @Autowired
    CustomerService customerService;

    @Autowired
    Dashboard dashboard;

    @Autowired
    LoginPage loginPage;

    /**
     * Creates new form Login
     */
    public LoginPage() {
        initComponents();
        scanner = SecugenScanner.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        WelcomeHeader = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerCodeTextField = new javax.swing.JTextPane();
        CustomerCodeHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeHeader.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        WelcomeHeader.setText("Welcome");

        submitButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        submitButton.setText("Continue");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        customerCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerCodeTextFieldKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(customerCodeTextField);

        CustomerCodeHeader.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CustomerCodeHeader.setText("Customer code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CustomerCodeHeader)
                                        .addComponent(WelcomeHeader))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(100, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(submitButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(WelcomeHeader)
                                .addGap(27, 27, 27)
                                .addComponent(CustomerCodeHeader)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(submitButton)
                                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>


    private int verifyPrints() {
        JOptionPane.showMessageDialog(jScrollPane1, "Place finger on scanner and Scan fingerprints...");

        scanner.sleep(1);
        byte[] scannedPrint = scanner.captureBytes();

        for (int i = 0; i < prints.size(); i++) {

            if (scanner.match(scannedPrint, prints.get(i).getPrintObject())) {
                numberOfMatchedPrints++;
                System.out.println(numberOfMatchedPrints);
                prints.remove(i);
                JOptionPane.showMessageDialog(jScrollPane1, "Fingerprint matched");
                System.out.println("Match Found: " + numberOfMatchedPrints);
                if (numberOfMatchedPrints == numberOfPrintsToValidate) {
                    dashboard.setVisible(true);
//            Customer activeAccount = foundCustomer;

                }
                return 1;
            }
            else  {
                JOptionPane.showMessageDialog(jScrollPane1, "Could not match prints. Please try logging in again");
                loginPage.setVisible(false);
                break;
            }

//            else if (!scanner.match(scannedPrint, prints.get(i).getPrintObject())){
//                JOptionPane.showMessageDialog(jScrollPane1,"Fingerprint matching failed");
//                System.out.println("Done here");
//                break;
//            }
        }
        return 0;
    }

    private void resetPrintsCounts() {
        numberOfMatchedPrints = 0;
        prints = new ArrayList<>();
    }


    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resetPrintsCounts();
        foundCustomer = customerService.searchCustomerByCode(customerCodeTextField.getText().trim());
        if (foundCustomer == null) {
            JOptionPane.showMessageDialog(jScrollPane1, "Customer not found");
            return;
        }

        prints = foundCustomer.getFingerprints();

        for (int i = 0; i < numberOfPrintsToValidate; i++) {
            int result = verifyPrints();
            if(result == 0){
                break;
            }
        }
    }

    private void customerCodeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel CustomerCodeHeader;
    private javax.swing.JLabel WelcomeHeader;
    private javax.swing.JTextPane customerCodeTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel2;

    // End of variables declaration
}
