/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectdummy.dummy.project.component;/*

/**
 *
 * @author uchen
 */

import com.projectdummy.dummy.project.Scanner.SecugenScanner;
import com.projectdummy.dummy.project.entity.Customer;
import com.projectdummy.dummy.project.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

@Component
public class Registration extends JFrame {


    Customer customer;

    @Autowired
    CustomerService customerService;

    @Autowired
    WelcomePage welcomePage;

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

    /**
     * Creates new form NewJFrame
     */



    public Registration() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        customer = new Customer();
    }

//    @PostConstruct
//    public void init(){
//
//    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        RegistrationHeader = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FirstNameTextField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        LastNameTextField = new javax.swing.JTextPane();
        AddressLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AddressTextField = new javax.swing.JTextPane();
        PhoneNumberLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PhoneNumberTextField = new javax.swing.JTextPane();
        CapturePrintsButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        GenderTextField = new javax.swing.JTextPane();
        EmailLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        EmailTextField = new javax.swing.JTextPane();
        DOBLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        DOBTextField = new javax.swing.JTextPane();
        MotherMaidenNameLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        MotherMaidenNameTextField = new javax.swing.JTextPane();
        AccountNumberLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        AccountNumberTextField = new javax.swing.JTextPane();
        fingerPanel = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrationHeader.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        RegistrationHeader.setText("Registration");

        FirstNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        FirstNameLabel.setText("First name: ");

        LastNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LastNameLabel.setText("Last name: ");

        SubmitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        FirstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstNameTextFieldKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(FirstNameTextField);

        LastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LastNameTextFieldKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(LastNameTextField);

        AddressLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AddressLabel.setText("Address: ");

        AddressTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddressTextFieldKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(AddressTextField);

        PhoneNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PhoneNumberLabel.setText("Phone no: ");

        PhoneNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumberTextFieldKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(PhoneNumberTextField);

        CapturePrintsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapturePrintsButton.setText("Capture Prints");
        CapturePrintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturePrintsButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Prints Preview");

        GenderLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GenderLabel.setText("Gender:");

        jScrollPane5.setViewportView(GenderTextField);

        EmailLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmailLabel.setText("Email:");

        EmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailTextFieldKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(EmailTextField);

        DOBLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DOBLabel.setText("Date of Birth:");

        DOBTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DOBTextFieldKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(DOBTextField);

        MotherMaidenNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MotherMaidenNameLabel.setText("Mother's maiden name:");

        MotherMaidenNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MotherMaidenNameTextFieldKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(MotherMaidenNameTextField);

        AccountNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AccountNumberLabel.setText("Account number: ");

        AccountNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AccountNumberTextFieldKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(AccountNumberTextField);

        fingerPanel.setEnabled(true);
        fingerPanel.setBackground(new Color(0x999999));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(FirstNameLabel)
                                                        .addComponent(LastNameLabel)
                                                        .addComponent(GenderLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(317, 317, 317)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(EmailLabel)
                                                                        .addComponent(DOBLabel)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(469, 469, 469)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(AccountNumberLabel)
                                                                        .addComponent(MotherMaidenNameLabel))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(AddressLabel)
                                                                .addGap(9, 9, 9)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(56, 56, 56)
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(25, 25, 25)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(333, 333, 333)
                                                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(PhoneNumberLabel))))
                                .addContainerGap(128, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(RegistrationHeader)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(ClearButton)
                                                .addGap(110, 110, 110)
                                                .addComponent(CapturePrintsButton))
                                        .addComponent(fingerPanel)
                                        .addGroup(layout.createSequentialGroup()))

                                .addGap(118, 118, 118)
                                .addComponent(SubmitButton)
                                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(88, 88, 88)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(FirstNameLabel)
                                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(8, 8, 8)
                                                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(LastNameLabel)
                                                                                        .addGap(45, 45, 45))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(40, 40, 40)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(DOBLabel)
                                                                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(GenderLabel)
                                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(MotherMaidenNameLabel)))
                                                        .addComponent(RegistrationHeader))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(AddressLabel)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(AccountNumberLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(5, 5, 5)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                                .addComponent(PhoneNumberLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SubmitButton)
                                        .addComponent(CapturePrintsButton)
                                        .addComponent(ClearButton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fingerPanel)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        customer.setFirstName(FirstNameTextField.getText());
        customer.setLastName(LastNameTextField.getText());
        customer.setAddress(AddressTextField.getText());
        customer.setEmail(EmailTextField.getText());
        customer.setPhoneNumber(PhoneNumberTextField.getText());
        customer.setGender(GenderTextField.getText());
        customer.setDob(DOBTextField.getText());
        customer.setMothersMaidenName(MotherMaidenNameTextField.getText());
        customer.setAccountNumber(AccountNumberTextField.getText());
        Customer savedCustomer = customerService.saveCustomer(customer);
        JOptionPane.showMessageDialog(jScrollPane2, "Please save your customer ID: "+savedCustomer.getCustomerCode());
        clear();
        welcomePage.setVisible(true);
    }

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        clear();
    }

    private void resetFingerPrintDisplay(){
        fingerPanel.removeAll();
        fingerPanel.revalidate();
        fingerPanel.repaint();

    }

    private void clear(){
        customer = new Customer();
        resetFingerPrintDisplay();
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        AddressTextField.setText("");
        PhoneNumberTextField.setText("");
        EmailTextField.setText("");
        GenderTextField.setText("");
        DOBTextField.setText("");
        MotherMaidenNameTextField.setText("");
        AccountNumberTextField.setText("");
    }


    private void PhoneNumberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setPhoneNumber(PhoneNumberTextField.getText());
    }

    private void AddressTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setAddress(AddressTextField.getText());
    }

    private void LastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setLastName(LastNameTextField.getText());
    }

    private void FirstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setFirstName(FirstNameTextField.getText());
    }

    private void CapturePrintsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        SecugenScanner scanner = SecugenScanner.getInstance();
        byte[] bytesOfImage = scanner.captureBytes();
        customer.addFingerprint(bytesOfImage);

        addPrintToView(scanner.toImage(bytesOfImage));
    }

    private void addPrintToView(BufferedImage image){
        ImageIcon pimage = new ImageIcon(image);

        ImageIcon scaledImage = new ImageIcon(pimage.getImage().getScaledInstance(pimage.getIconWidth()/2,pimage.getIconHeight()/2, Image.SCALE_SMOOTH));

        JLabel labelledImage = new JLabel(scaledImage);



        fingerPanel.add(labelledImage);
        fingerPanel.revalidate();
        fingerPanel.repaint();

    }

    private void EmailTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setEmail(EmailTextField.getText());
    }

    private void DOBTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setDob(DOBTextField.getText());
    }

    private void MotherMaidenNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setMothersMaidenName(MotherMaidenNameTextField.getText());
    }

    private void AccountNumberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        customer.setAccountNumber(AccountNumberTextField.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JTextPane AccountNumberTextField;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextPane AddressTextField;
    private javax.swing.JButton CapturePrintsButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTextPane DOBTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextPane EmailTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextPane FirstNameTextField;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextPane GenderTextField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextPane LastNameTextField;
    private javax.swing.JLabel MotherMaidenNameLabel;
    private javax.swing.JTextPane MotherMaidenNameTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextPane PhoneNumberTextField;
    private javax.swing.JLabel RegistrationHeader;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel fingerPanel;

    // End of variables declaration
}
