//package com.projectdummy.dummy.project.component;
//
///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//
//import com.projectdummy.dummy.project.entity.Customer;
//import com.projectdummy.dummy.project.repository.ICustomerRepository;
//import com.projectdummy.dummy.project.service.CustomerService;
//import org.apache.catalina.util.CustomObjectInputStream;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Component;
//
//import javax.swing.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
///**
// * @author uchen
// */
//@Component
//public class Dashboard extends JFrame {
//
//    @Autowired
//    private Customer customer;
//
//    @Autowired
//    private CustomerService customerService;
//
//    @Autowired
//    private LoginPage loginPage;
//
//    /**
//     * Creates new form Dashboard
//     */
//    public Dashboard() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        welcomeHeader = new javax.swing.JLabel();
//        depositCashButton = new javax.swing.JButton();
//        checkBalance = new javax.swing.JButton();
//        withdrawButton = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        welcomeHeader.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
//        welcomeHeader.setText("Welcome");
//
//        depositCashButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        depositCashButton.setText("Deposit Cash");
//        depositCashButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                depositCashButtonActionPerformed(evt);
//            }
//        });
//
//        checkBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        checkBalance.setText("Check Balance");
//        checkBalance.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                checkBalanceActionPerformed(evt);
//            }
//        });
//
//        withdrawButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        withdrawButton.setText("Withdraw");
//        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                withdrawButtonActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(230, 230, 230)
//                                .addComponent(welcomeHeader)
//                                .addGap(0, 0, Short.MAX_VALUE))
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(52, 52, 52)
//                                .addComponent(withdrawButton)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
//                                .addComponent(depositCashButton)
//                                .addGap(69, 69, 69))
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(190, 190, 190)
//                                .addComponent(checkBalance)
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(44, 44, 44)
//                                .addComponent(welcomeHeader)
//                                .addGap(49, 49, 49)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(depositCashButton)
//                                        .addComponent(withdrawButton))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
//                                .addComponent(checkBalance)
//                                .addGap(76, 76, 76))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//
//        String input = JOptionPane.showInputDialog("Enter the amount to withdraw");
//        Long parsedInput = Long.parseLong(input);
//        if (parsedInput <= customer.getBalance()) {
//            JOptionPane.showMessageDialog(jTextField1, "Insufficient Account Balance");
//        } else {
////            long newBalance =
//            JOptionPane.showMessageDialog(jTextField1, "You have successfully withdrawn " +  parsedInput + " and your new balance is " );
//        }
//    }
//
//    private void depositCashButtonActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        JTextField  inputBox = new JTextField();
//        String text = JOptionPane.showInputDialog("Input amount to deposit");
//        long deposit = Long.parseLong(text);
//        customer.setBalance(deposit);
//
//
////        customerService.updateCustomer(customer,uid);
//        JOptionPane.showMessageDialog(inputBox, "You have deposited " + deposit + ", your new balance is " + customer.getBalance());
//    }
//
//    private void checkBalanceActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(jTextField1, "Your balance is " + customer.getBalance());
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton checkBalance;
//    private javax.swing.JButton depositCashButton;
//    private javax.swing.JLabel welcomeHeader;
//    private javax.swing.JButton withdrawButton;
//    private javax.swing.JTextField jTextField1;
//    // End of variables declaration
//}
